from pathlib import Path


def get_dashboard_ctx():
    """Build a read-only StorageContext for dashboard use."""
    from urbantrips.config.config import load_config
    from urbantrips.storage.context import build_storage_context
    from urbantrips.dashboard.dash_storage import (
        leer_configs_generales,
        _get_base_config_path,
    )

    # Ensure the autogenerated config exists (leer_configs_generales copies it
    # from the per-corrida autogenerado when missing) and load that one, since
    # it carries the resolved DB aliases the dashboard reads from.
    leer_configs_generales(autogenerado=True)
    autogen_path = (
        _get_base_config_path().parent
        / "configuraciones_generales_autogenerado.yaml"
    )
    config = load_config(autogen_path)
    return build_storage_context(config)
