"""
Non-Streamlit storage and query helpers for the UrbanTrips dashboard.

This module has no dependency on ``streamlit`` and can be imported in contexts
where Streamlit is not running (scripts, tests, etc.).  Functions that require
``st.session_state`` (e.g. ``leer_alias``, ``iniciar_conexion_db``) remain in
``dash_utils`` because they are Streamlit-aware by design.
"""

from __future__ import annotations

import logging
import os
import shutil
import yaml
import duckdb
import pandas as pd
from pathlib import Path

from urbantrips.utils.paths import get_paths

logger = logging.getLogger(__name__)


def _get_base_config_path() -> Path:
    """Return the non-autogenerated config path, respecting URBANTRIPS_CONFIG env var."""
    env_config = os.environ.get("URBANTRIPS_CONFIG")
    if env_config:
        return Path(env_config)
    return get_paths().config_file


def resolve_db_aliases(configs: dict) -> dict:
    """Alias único para las 4 bases (data / insumos / dash / general).

    En esta versión el autogenerado y las DBs por-corrida quedaron obsoletos:
    todo se guarda bajo un solo alias = alias_db_insumos (con alias_db como
    fallback histórico). Las claves por-corrida (alias_db_data,
    alias_db_dashboard) ya no aplican.
    """
    alias = configs.get("alias_db_insumos") or configs.get("alias_db") or ""
    return {"data": alias, "insumos": alias, "dash": alias, "general": alias}


def get_project_root() -> Path:
    """Return the project root (parent of the configs dir).

    When URBANTRIPS_CONFIG is set the config file is expected to live at
    <project_root>/configs/<filename>.yaml, so the project root is two levels up.
    Falls back to CWD otherwise.
    """
    env_config = os.environ.get("URBANTRIPS_CONFIG")
    if env_config:
        return Path(env_config).resolve().parent.parent
    return Path(".")


def _load_yaml_simple(path: Path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
    except UnicodeDecodeError:
        with open(path, "r", encoding="latin-1") as f:
            data = yaml.safe_load(f)
    return data if data else {}


def _find_first_valid_yaml(autogen_dir: Path, base_path: Path | None = None):
    if base_path is None:
        base_path = _get_base_config_path()
    if not base_path.exists():
        raise FileNotFoundError(f"No existe {base_path}")

    base = _load_yaml_simple(base_path)

    try:
        tmp = base["corridas"][0]
    except Exception as e:
        raise KeyError("No se pudo obtener base['corridas'][0]") from e

    origen = autogen_dir / f"configuraciones_generales_autogenerado_{tmp}.yaml"

    if not origen.exists():
        raise FileNotFoundError(f"No existe el autogenerado esperado: {origen}")

    if origen.stat().st_size == 0:
        raise ValueError(f"El autogenerado esperado está vacío: {origen}")

    return origen


def leer_configs_generales(autogenerado=True):
    base_path = _get_base_config_path()
    config_dir = base_path.parent
    autogen_dir = config_dir / "autogenerados"

    if autogenerado:
        path = config_dir / "configuraciones_generales_autogenerado.yaml"
    else:
        path = base_path

    logger.debug("Loading config from %s", path)

    if autogenerado and ((not path.exists()) or path.stat().st_size == 0):
        origen = _find_first_valid_yaml(autogen_dir, base_path)
        shutil.copy(origen, path)

    try:
        return _load_yaml_simple(path)
    except yaml.YAMLError as e:
        logger.error("Error YAML: %s", e)

        if autogenerado:
            origen = _find_first_valid_yaml(autogen_dir, base_path)
            shutil.copy(origen, path)
            return _load_yaml_simple(path)

        return {}


def normalize_vars(tabla):
    if "dia" in tabla.columns:
        tabla.loc[tabla.dia == "weekday", "dia"] = "Hábil"
        tabla.loc[tabla.dia == "weekend", "dia"] = "Fin de semana"
    if "day_type" in tabla.columns:
        tabla.loc[tabla.day_type == "weekday", "day_type"] = "Hábil"
        tabla.loc[tabla.day_type == "weekend", "day_type"] = "Fin de semana"
    if "tipo_dia" in tabla.columns:
        tabla.loc[tabla.tipo_dia == "Dia habil", "tipo_dia"] = "Hábil"
    if "nombre_linea" in tabla.columns:
        tabla["nombre_linea"] = tabla["nombre_linea"].str.replace(" -", "")
    if "Modo" in tabla.columns:
        tabla["Modo"] = tabla["Modo"].str.capitalize()
    if "modo" in tabla.columns:
        tabla["modo"] = tabla["modo"].str.capitalize()
    return tabla


def _fetch_sql_dataframe(conn, query, params=None):
    if isinstance(conn, duckdb.DuckDBPyConnection):
        return conn.execute(query, params).fetchdf()
    return pd.read_sql_query(query, conn, params=params)
