# PARAMETROS GENERALES DE URBANTRIPS - 10k tarjetas issue 51
# Resolucion H3: resolucion del hexagono. La resolucion 8 tiene lados de 460 metros.  Resolucion 9 tiene 174 metros y la  10 tiene  65 metros
resolucion_h3: 8

# Alias a utilizar en las db de datos y de insumos
alias_db_data: jn
alias_db_insumos: desarrollo

# Proyeccion de coordenadas en metros a utilizar  
epsg_m: 9265

# Filtro de coordenadas en formato minx, miny, maxx, maxy 
filtro_latlong_bbox:
    minx: -59.3
    miny: -35.5
    maxx: -57.5
    maxy: -34.0 

#Especificar el formato fecha presente en todos los dataset
formato_fecha: "%d/%m/%Y %H:%M:%S"

# PARAMETROS PARA IMPUTACION DE DESTINOS 
# Distancia maxima tolerable entre destino imputado y siguiente transaccion (en metros)
tolerancia_parada_destino: 2200

# Imputar utilizando la parada de la linea de orige que minimice la distancia con respecto a la siguiente transaccion o solo la siguiente transaccion
imputar_destinos_min_distancia: True


# PARAMETROS DE TRANSACCIONES
# Nombre del archivo con las transacciones a consumir
nombre_archivo_trx: transacciones_amba_20221109_jn.csv

# Nombre de las variables necesarias por Urbantrips tal cual aparecen en el archivo
nombres_variables_trx:
    id_trx: id
    fecha_trx: FECHATRX 
    id_tarjeta_trx: NROTARJETA
    modo_trx: modo
    hora_trx: 
    id_linea_trx: IDLINEA
    id_ramal_trx: RAMAL 
    interno_trx: INTERNO
    orden_trx:  
    latitud_trx: latitud 
    longitud_trx: longitud
    factor_expansion:   

#Indicar si la informacion sobre la hora está en una columna separada. En nombres_variables debe indicarse el nombre. Dejar vacío en caso contrario 
columna_hora: False 

# Indicar que criterio se desea utilizar para ordenar las transacciones en el tiempo. 
#     Puede utilizarse el campo fecha: en ese caso debe tener informacion hasta el minuto al menos, y se debe especificar una ventana de tiempo en minutos en ventana_viajes para agrupar etapas en un viaje
#     Puede utilizarse el campo orden_trx: este campo debe tener  entero secuencial que ordena las transacciones. Debe comenzar en cero cuando se comienza un nuevo viaje, e incrementear con cada nueva etapa en ese viaje

# Criterio para ordenar las transacciones en el tiempo. 'fecha_completa' utiliza el campo dado en fecha_trx mientras que `orden_trx` utiliza un entero incremental que se reinicia con cada viaje   
ordenamiento_transacciones: fecha_completa 

# Cantidad de minutos de la ventana de tiempo para considerar diferentes etapas dentro de un mismo viaje
ventana_viajes: 120

# Cantidad de minutos de la ventana de tiempo para considerar diferentes transacciones como una sola
ventana_duplicado: 5 

# Tipo de transacciones a elminar por no considerare usos en transporte publico. Indicar la columna y los valores para cada columna
tipo_trx_invalidas:
    CODIGOROL:
        - 'CHECK OUT SIN CHECKIN'
        - 'CHECK OUT'

# Especificar como se nombra a los modos en los archivos  
modos:
    autobus: COLECTIVO
    tren: TREN
    metro: SUBTE
    tranvia:
    brt:
 
 
# PARAMETROS DE POSICIONAMIENTO GPS

# Utilizar un dataset de posicionamiento GPS para geolocalizar transacciones
geolocalizar_trx: False

# Nombre del archivo con los posicionamientos GPS a consumir
nombre_archivo_gps: gps_amba_20221109_jn.csv

# Nombre de las variables necesarias por Urbantrips tal cual aparecen en el archivo
nombres_variables_gps:
    id_gps: DTSN
    id_linea_gps: IDLINEA
    id_ramal_gps: C_LD_ID
    interno_gps: INTERNO
    fecha_gps: DATE_TIME
    latitud_gps: LATITUDE
    longitud_gps:  LONGITUDE
    service_type_gps:
        TYPE:
            start_service: 7
            finish_service: 8
    velocity_gps: VELOCITY

trust_service_type_gps: False

# PARAMETROS DE LINEAS, RAMALES, RECORRIDOS Y PARADAS 

# Las lineas a ser utilizadas se subdividen en ramales?
lineas_contienen_ramales: True

# Nombre del archivo con la metadada de lineas y/o ramales
nombre_archivo_informacion_lineas: metadata_lineas_jn.csv

# Nombre del archivo con las rutas de las lineas y/o ramales
recorridos_geojson: recorridos_jn.geojson

# Nombre del archivo con las paradas para todas las lineas y/o ramales con orden y node_id 
nombre_archivo_paradas: stops_jn.csv

 
# Poner geo1 el nombre del archivo geojson, var1 el nombre de la variable que contiene la etiqueta a utilizar, orden1 el orden de las etiquetas en los graficos
zonificaciones:
