# Archivo de configuración para urbantrips

corridas: ['20251013', '20251018', '20251015']                     # Listar los nombres de las corridas ['lunes','martes'], deben coincidir con los archivos trx y gps,por ej lunes_trx.csv, lunes_gps.csv, martes_trx.csv, martes_gps.csv

alias_db_insumos: "db"                                             # nombre del sqlite donde se guardan los insumos generales

# Nombre de columnas en el archivo de transacciones
nombres_variables_trx: 
    id_trx: "ID_TRX"                                               # columna con id único del archivo de transacciones
    fecha_trx: "FECHATRX"                                          # columna con fecha de la transacción
    id_tarjeta_trx: "NROTARJETA"                                   # columna con id de la tarjeta
    modo_trx: "MODO"                                               # columna con modo de transporte
    hora_trx:                                                      # columna con hora de la transacción
    id_linea_trx: "IDLINEA"                                        # columna con el id de la línea
    id_ramal_trx: "RAMAL"                                          # columna con el ramal de la línea
    interno_trx: "INTERNO"                                         # columna con interno de la línea
    orden_trx:                                                     # columna con el orden de la transacción (si falta hora/minuto en fecha_trx)
    genero:                                                        # Indica el género asignado a la tarjeta
    tarifa:                                                        # Indica el tipo de tarifa asignado a la transacción
    latitud_trx: "LATITUDE"                                        # columna con la latitud de la transacción
    longitud_trx: "LONGITUDE"                                      # columna con longitud de la transacción
    factor_expansion:                                              # columna con el factor de expansión

# Parámetros de transacciones
ordenamiento_transacciones: "fecha_completa"                       # especifica si ordena transacciones por fecha ("fecha_completa") o por variable orden_trx ("orden_trx") en la tabla nombres_variables_trx
ventana_viajes: 120                                                # ventana de tiempo para que una transacción sea de un mismo viaje (ej. 60 minutos)
ventana_duplicado: 5                                               # ventana de tiempo si hay duplicado de transacción (ej. Viaje con acompañante)

# Elimina transacciones inválidas de la tabla de transacciones
tipo_trx_invalidas:                                                # Lista con el contenido a eliminar de la variable seleccionada

# Imputación de destino
tolerancia_parada_destino: 2200                                    # Distancia para la validación de los destinos (metros)
imputar_destinos_min_distancia: True                               # Busca la parada que minimiza la distancia con respecto a la siguiente trancción

# Parámetros geográficos
resolucion_h3: 9                                                   # Resolución de los hexágonos
epsg_m: 5347                                                       # Parámetros geográficos: crs

formato_fecha: "%Y-%m-%d %H:%M:%S"                                 # Configuración fecha y hora
columna_hora: False                                                

usa_archivo_gps: True                                              # Si existe un archivo gps
geolocalizar_trx: False                                            

# Nombre de columnas en el archivo de GPS
nombres_variables_gps: 
    id_gps: "ID_GPS"                                               
    id_linea_gps: "IDLINEA"                                        
    id_ramal_gps: "C_LD_ID"                                        
    interno_gps: "INTERNO"                                         
    fecha_gps: "DATE_TIME"                                         
    latitud_gps: "LATITUDE"                                        
    longitud_gps: "LONGITUDE"                                      
    velocity_gps:                                                  
    distance_servicio_mts_gps:                                     # Distancia gps en metros
    distance_servicio_mts_agg_gps:                                 # Distancia gps agregada en metros
    id_servicio_gps:                                               # id del servicio
    servicios_gps: "TYPE"                                          # Indica cuando se abre y cierra un servicio
    dominio_gps:                                                   # Dominio o Mounting kit del vehículo

# Información para procesamiento de líneas
nombre_archivo_informacion_lineas: "elr_20251015.csv"              # Archivo .csv con lineas, debe contener ("id_linea", "nombre_linea", "modo")
lineas_contienen_ramales: True                                     # Especificar si las líneas de colectivo contienen ramales
nombre_archivo_paradas:                                            
imprimir_lineas_principales: 5                                     # Imprimir las lineas principales - "All" imprime todas las líneas

# Servicios GPS
utilizar_servicios_gps: True                                       # Especifica si ve van a utilizar los servicios GPS
valor_inicio_servicio: 7                                           # Valor de la variable que marca el inicio del servicio
valor_fin_servicio: 8                                              # Valor de la variable que marca el fin del servicio

modos: 
    autobus: "COLECTIVO"                                           
    tren: "TREN"                                                   
    metro: "SUBTE"                                                 
    tranvia:                                                       
    brt:                                                           
    cable:                                                         
    lancha: "LANCHAS"                                              
    otros:                                                         

# Capas geográficas con recorridos de líneas
recorridos_geojson: "recorridos.geojson"                           # archivo geojson con el trazado de las líneas de transporte público

filtro_latlong_bbox: 
    minx: -59.3                                                    
    miny: -35.5                                                    
    maxx: -57.5                                                    
    maxy: -34.0                                                    

# Zonificaciones
zonificaciones: 
    geo1: "partidos.geojson"                                       
    var1: "Partido"                                                
    orden1:                                                        
    geo2: "zonas_caba.geojson"                                     
    var2: "nombre_zona"                                            
    orden2:                                                        
    geo3:                                                          
    var3:                                                          
    orden3:                                                        
    geo4:                                                          
    var4:                                                          
    orden4:                                                        
    geo5:                                                          
    var5:                                                          
    orden5:                                                        

poligonos: "centros_de_transbordo.geojson"                         # Especificar una capa geográfica de polígonos en formato .geojson. El archivo requiere las siguientes columnas: ['id', 'tipo', 'geometry']. 'id' es el id o nombre del polígono, tipo puede ser 'poligono' o 'cuenca'.

tiempos_viaje_estaciones:                                          # Especificar una tabla de tiempo de viaje en minutos entre estaciones para modos sin gps

