# urbantrips/storage/ports.py
from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol, runtime_checkable

import pandas as pd
import geopandas as gpd


@dataclass(frozen=True)
class BatchSpec:
    """Describes one user-partition for parallel processing.

    The adapter maps batch_id/total_batches to actual user ID hash buckets.
    batch=None in port methods means 'all users' (used for aggregation steps).
    """
    batch_id: int
    total_batches: int


@runtime_checkable
class DataPort(Protocol):
    """Operational run data (_data database)."""

    def get_user_batches(self, n_batches: int) -> list[BatchSpec]: ...

    def get_run_days(self) -> pd.DataFrame: ...
    def save_run_days(self, df: pd.DataFrame) -> None: ...

    def get_transactions(self, batch: BatchSpec | None = None, run_days: list[str] | None = None) -> pd.DataFrame: ...
    def get_transactions_for_chunk(self, batch_ids: list[int], total_batches: int, run_days: list[str] | None = None) -> pd.DataFrame: ...
    def save_transactions(self, df: pd.DataFrame, batch: BatchSpec | None = None) -> None: ...

    def get_legs(self, batch: BatchSpec | None = None) -> pd.DataFrame: ...
    def save_legs(self, df: pd.DataFrame, batch: BatchSpec | None = None) -> None: ...
    def update_leg_trip_ids(self, df: pd.DataFrame, dia: str | None = None) -> None: ...
    def replace_legs_for_days(self, df: pd.DataFrame, days: list[str]) -> None: ...

    def get_trips(self, batch: BatchSpec | None = None) -> pd.DataFrame: ...
    def save_trips(self, df: pd.DataFrame, batch: BatchSpec | None = None) -> None: ...

    def get_users(self, batch: BatchSpec | None = None) -> pd.DataFrame: ...
    def save_users(self, df: pd.DataFrame, batch: BatchSpec | None = None) -> None: ...

    def get_gps(self) -> pd.DataFrame: ...
    def save_gps(self, df: pd.DataFrame) -> None: ...
    def geolocate_raw_transactions_from_gps(self, lineas_contienen_ramales: bool) -> None: ...

    # staging del ingest de gps (ver process_and_upload_gps_table)
    def reset_gps_raw(self) -> None: ...
    def save_gps_raw_chunk(self, df: pd.DataFrame) -> None: ...
    def prepare_gps_from_raw(
        self, dedup_subset: list[str], id_offset: int, odometro: str | None
    ) -> int: ...
    def gps_prep_has_service_start(self) -> bool: ...
    def gps_prep_days(self) -> list[str]: ...
    def get_gps_prep_day(self, dia: str) -> pd.DataFrame: ...
    def clear_gps_staging(self) -> None: ...

    def delete_run_days(self, days: list[str]) -> None: ...
    def execute(self, sql: str) -> None: ...
    def has_rows(self, table_name: str, where: str | None = None) -> bool: ...

    def get_indicators(self) -> pd.DataFrame: ...
    def save_indicators(self, df: pd.DataFrame) -> None: ...

    def get_vehicle_expansion_factors(self) -> pd.DataFrame: ...
    def save_vehicle_expansion_factors(self, df: pd.DataFrame) -> None: ...

    def get_services(self) -> pd.DataFrame: ...
    def save_services(self, df: pd.DataFrame) -> None: ...

    def get_line_transactions(self) -> pd.DataFrame: ...
    def save_line_transactions(self, df: pd.DataFrame) -> None: ...

    def get_max_id(self, table: str) -> int: ...
    def query(self, sql: str) -> pd.DataFrame: ...
    def save_raw(self, df: pd.DataFrame, table_name: str) -> None: ...
    def append_raw(self, df: pd.DataFrame, table_name: str) -> None: ...
    def get_raw(self, table_name: str) -> pd.DataFrame: ...

    def save_raw_chunk(self, df: pd.DataFrame) -> None: ...
    def clear_raw(self) -> None: ...
    def standardize_raw_to_transacciones(self, n_batches: int, id_offset: int) -> None: ...
    def get_transactions_for_batch(self, batch: "BatchSpec") -> pd.DataFrame: ...
    def get_legs_for_batch(self, batch: "BatchSpec") -> pd.DataFrame: ...


@runtime_checkable
class InsumoPort(Protocol):
    """Static reference data (_insumos database)."""

    def get_routes(self) -> gpd.GeoDataFrame: ...
    def get_stops(self) -> pd.DataFrame: ...
    def get_zones(self) -> gpd.GeoDataFrame: ...
    def get_metadata_lineas(self) -> pd.DataFrame: ...
    def get_matrix_validation(self) -> pd.DataFrame: ...
    def get_travel_times_stations(self) -> pd.DataFrame: ...

    def get_matriz_paradas(self) -> pd.DataFrame: ...
    def get_matriz_paradas_dias(self) -> list[str]: ...
    def save_matriz_paradas(self, df: pd.DataFrame, dias: list[str]) -> None: ...

    def get_metadata_ramales(self) -> pd.DataFrame: ...
    def save_metadata_ramales(self, df: pd.DataFrame) -> None: ...

    def save_routes(self, df: gpd.GeoDataFrame) -> None: ...
    def save_stops(self, df: pd.DataFrame) -> None: ...
    def save_zones(self, df: gpd.GeoDataFrame) -> None: ...
    def save_matrix_validation(self, df: pd.DataFrame) -> None: ...
    def save_travel_times_stations(self, df: pd.DataFrame) -> None: ...
    def save_metadata_lineas(self, df: pd.DataFrame) -> None: ...

    def execute(self, sql: str) -> None: ...
    def query(self, sql: str) -> pd.DataFrame: ...
    def save_raw(self, df: pd.DataFrame, table_name: str) -> None: ...
    def get_raw(self, table_name: str) -> pd.DataFrame: ...
    def append_raw(self, df: pd.DataFrame, table_name: str) -> None: ...
    def has_routes(self) -> bool: ...


@runtime_checkable
class DashPort(Protocol):
    """Pre-computed dashboard tables (_dash database). Write-once, read-many."""

    def save_indicator(self, df: pd.DataFrame, name: str) -> None: ...
    def get_indicator(self, name: str) -> pd.DataFrame: ...
    def list_indicators(self) -> list[str]: ...
    def execute(self, sql: str) -> None: ...
    def query(self, sql: str) -> pd.DataFrame: ...
    def append_raw(self, df: pd.DataFrame, table_name: str) -> None: ...


@runtime_checkable
class GeneralPort(Protocol):
    """Cross-run metadata (_general database)."""

    # log de progreso por corrida/día (formato long, un ts por step)
    def get_run_log(self) -> pd.DataFrame: ...
    def register_step(self, alias: str, corrida: str, dias: list[str], step: str, config_yaml: str | None = None) -> None: ...
    def delete_corrida_log(self, alias: str, corridas: list[str]) -> None: ...
    def clear_runs(self) -> None: ...

    # copia del yaml que produjo la corrida (deja la base auto-descriptiva)
    def save_config_snapshot(self, alias: str | None, corrida: str, archivo: str | None, contenido: str) -> None: ...
    def get_config_snapshot(self) -> pd.DataFrame: ...

    # compat legacy (write_transactions_to_db / procesar_transacciones)
    def get_completed_runs(self) -> pd.DataFrame: ...
    def register_run(self, alias: str, process: str) -> None: ...
    def run_exists(self, alias: str) -> bool: ...

    def execute(self, sql: str) -> None: ...
    def query(self, sql: str) -> pd.DataFrame: ...
    def append_raw(self, df: pd.DataFrame, table_name: str) -> None: ...
    def get_raw(self, table_name: str) -> pd.DataFrame: ...
